### ISSUE TITLE
Small rodents issues

### ISSUE THREAD

**Issue by JotablancoA** [BiologicalRecordsCentre/MammalNet-Europe#44]
When you use “small rodent” (unknown) option, the family that appear in the web is Sciuridae. Some users were not comfortable with this output, mainly because the first image of sciuridae is a squirrel and could not be adequate for a small rodent. Perhaps it is a translation problem, in this case should be modify the Spanish translation.  
At the moment users can not delete or edit the records in the web, see previous issue submited

**Comment by johnvanbreda** [comment]
@DavidRoy I think this is an app issue? The list kept on the warehouse just has Sciuridae without any associated common names.

**Comment by kazlauskis** [comment]
Is the issue here to show 'Small rodent' instead of Sciuridae within the website? If so, then adding a common name to the warehouse [taxa](https://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/440914) should be enough, I think. 

This common name for Sciuridae as well as all the other species common names and translations are within the Transifex site.

**Comment by DavidRoy** [comment]
I've added a common name to the warehouse species list for Scuridae.
@johnvanbreda is there a need to trigger an update to the cache-tables and ES index for this to be picked up on explore reports?

**Comment by JotablancoA** [comment]
Now when you select "small rodent" it is classified as sciuridae.
We have thee options;
1) change the common name to squirrel (unknown)
2) Change de family output
3) Eliminate this group

When you use option 1) we can modify the common name in other languages

**Comment by DavidRoy** [comment]
I've implemented option (1) as 'small rodent' is clearly wrong on the website.  It will take some time for the update to appear on the website reports - after background processes have run.

However, is there a more fundamental discussion about the app species list.
@JotablancoA Should choosing 'small rodent (unknown species)' within iMammalia create a database record of taxon=Scuridae?  Should the app change to 'squirrel (unknown species)'

**Comment by JotablancoA** [comment]
In Spanish, the mental image of small rodents is associated with the mouse,
voles, or shrew, no one associates it with squirrels. It is not clear to me
if it occurs in a similar way with the English language. If we change that
group to squirrels, do you miss any general groups that we're not
considering?

For me is ok change to squirrels in the app...we can request to user delete
or edit those records in the website

**Comment by DavidRoy** [comment]
We also associate small rodents with mice, voles or shrews in English.

@JotablancoA Just to confirm next steps:
1. remove 'small rodents (unknown)' from the app list
2. add 'squirrels (unknown)' to the app

For the existing records entered as 'small rodents (unknown)' can you advise on what they should be changed to 'Rodentia' (i.e. taxon level of order)?  I think it is better to make the change in the database rather than ask the recorders to edit their records

**Comment by johnvanbreda** [comment]
@DavidRoy to update the names in ES, there is a lookup text file used by Logstash which needs to be updated. I'll do this when you've settled on the exact changes.

**Comment by JotablancoA** [comment]
There is not consensus with this species name. Mainly because there are a
lot hybridizations and because there are different taxonomic approaches.
In addition could be possible to consider different groups for  corcega,
chipre, ceredeña-

This are the different options:
Ovis aries musimon
Ovis orientalis musimon
Ovis gmelini musimon
Ovis musimon

Probably the most accepted is:
Ovis orientalis musimon

However note that in this case in Chipre there is a other subspecie:  Ovis
orientalis ophion

**Comment by JotablancoA** [comment]
From Spain we still do not have access or possibility to edit our own records

**Comment by DavidRoy** [comment]
suggest this is closed as the 'small rodent' issues is resolved? I've bumped the editing records issue #49
