### ISSUE TITLE
Records not linked to country in ES index?

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/MammalNet-Europe#54]
Relates to: https://european-mammals.brc.ac.uk/en/records/explore/all

When I list all records in all locations  I currently get 2807, including a number in March from Germany.
When I list all records in Germany using the drop-down list on the page I find 1917, but NONE from March. At the end of Feb I had 1949 records in Germany 

This seems to relate to the records not being indexed against country?

**Comment by johnvanbreda** [comment]
This seems to be OK now - maybe it was affected by all the indexing Rich has been doing? I found the following counts for German records since 01/03 this morning using various approaches and I've managed to explain the differences:
103 records indexed in PostgreSQL.
102 records if I use a spatial query rather than the indexed locations. The single missing record is a record on a sand spit in the sea where the polygon has been simplified - therefore I think it's probably an anomaly in the data or locations update process rather than the code failing.
99 records in Elasticsearch. The 4 missing records are all new ones since yestarday afternoon when Rich updated Logstash to index the SSSIs. There was a mistake left in the config which meant Logstash was failing - I've notified Rich.
