### ISSUE TITLE
Mink naming 

### ISSUE THREAD

**Issue by GrahamCSmith** [BiologicalRecordsCentre/MammalNet-Europe#66]
There are three American mink records on the web site. All must have been redetermined from the generic small mustelid. Two are Mustela vison, and one is Neovison vison. The current preferred Latin name is Neovison vison. Can we stop redetermination as Mustela vison so the species naming is consistent?
No doubt genetics will re-name this in the future....

**Comment by johnvanbreda** [comment]
2 issues here - the redetermination is allowing selection of names from UKSI rather than the European mammals list. I've fixed that. The second issue is the European Mammals list only has Mustela vison, not Neovison for the name. 

@DavidRoy do you agree that I should:
1. Add a name "Neovison vison" to the European Mammals list.
2. Make "Mustela vison" a synonym of it.

After these changes, Mustela vison will still appear for selection but will have the correct preferred name. If we really want to block it we could set the allow_data_entry=false flag on Mustela vison.

**Comment by DavidRoy** [comment]
@johnvanbreda yes please

**Comment by johnvanbreda** [comment]
Done.
