### ISSUE TITLE
Species appearing twice on the web site.

### ISSUE THREAD

**Issue by GrahamCSmith** [BiologicalRecordsCentre/MammalNet-Europe#67]
Records 13052118 and 12572259 have been redetermined as stoats Mustela erminea. On the explore records species tab it appears twice, both stating a single records. This also occurs for pine marten, weasel, brown rat and coypu, as well as Talpa europaea (and this is called both the common mole and the European mole).
This appears to be an issue with redetermination from a generic record.

**Comment by johnvanbreda** [comment]
@GrahamCSmith this should be fixed now. It occurred because names were being erroneously re-determined against the UK list, which doesn't have a mapping to the European Mammals list so they were treated as 2 taxa by the report. I've updated the records which had this problem to point them back to the European list and had previously ensured the redetermination tool uses the European Mammals list.
