### ISSUE TITLE
Add missing species

### ISSUE THREAD

**Issue by Vilius-Stankaitis** [BiologicalRecordsCentre/MammalNet-Europe#72]
- [x] Martes foina Beech marten
- [x] Hydropotes inermis Chinese water deer 
- [x] Spermophilus pygmaeus Little souslik
- [x] Vormela peregusna Marbled polecat
- [x] Erinaceus concolor Southern white-breasted hedgehog
- [x] Apennine hare
- [x] Muskrat

**Comment by GrahamCSmith** [comment]
Muskrat: https://commons.wikimedia.org/wiki/File:Ondatra_zibethicus_FWS.jpg
Apennine hare: https://www.inaturalist.org/photos/88166717
Little souslik: https://www.inaturalist.org/photos/32173039
Chinese water deer: https://www.inaturalist.org/photos/78684823

**Comment by GrahamCSmith** [comment]
@kazlauskis a number of new images listed here
Marbled polecat: https://commons.wikimedia.org/wiki/File:Tigeriltis.jpg
Southern white breasted hedgehog: https://en.wikipedia.org/wiki/File:2008_Hedgehog_1020932.jpg
Improved beech marten photo: https://unsplash.com/photos/7D8O5dSBil4

**Comment by kazlauskis** [comment]
@GrahamCSmith thanks! We will add these to the app next week.

**Comment by GrahamCSmith** [comment]
@kazlauskis One correction to make with the maps. Since the re-determination of the eastern hedgehog into two species, the northern one E roumanicus should now have the map currently used by the southern one E concolor. The map for E concolor can remain blank (its limited to Greece and neighboring countries). I'll also get Jota to update the MammalNET info to match.

**Comment by kazlauskis** [comment]
OK, we'll update the maps.
