### ISSUE TITLE
Improve icon placement

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/MammalNet-Europe#9]
On explore reports, i.e. https://european-mammals.brc.ac.uk/explore/all-records.  The icons for altering the columns displayed is not in the ideal position.  Can this design be improved?

![imamm](https://user-images.githubusercontent.com/2699478/66416414-acfc8380-e9f5-11e9-9109-0b83593286f0.jpg)

**Comment by johnvanbreda** [comment]
The icons don't really have a space to sit in, so they are overlaid onto the top right of the grid. This is slightly more problematic due to the scrollbar occupying some space on the right. I've deployed the latest code though which improves the visual appearance of this quite a bit without actually moving the buttons.

**Comment by DavidRoy** [comment]
Thanks. That is an improvement.  Perhaps the fill for the icon box should be solid so that none of the underlying table heading shows?

**Comment by johnvanbreda** [comment]
I took a slightly different approach but it should look tidier now? The header now overlaps the space occupied by the scrollbar.

**Comment by DavidRoy** [comment]
works well, thanks
